### ISSUE TITLE
Crashes on windows

### ISSUE THREAD

**Issue by hardliner66** [togglebyte/florp-engine#2]
I tried the example code on windows but it crashes with the following error:

```
thread 'main' panicked at 'Original console mode not set', D:\CARGO\registry\src\github.com-1ecc6299db9ec823\crossterm-0.18.2\src\event\sys\windows.rs:38:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\florp_test.exe` (exit code: 101)
```

There already was a similar error in the crossterm repo: https://github.com/crossterm-rs/crossterm/issues/377

It seems like disabling mouse capture on windows doesn't quite work correctly.

**Comment by togglebyte** [comment]
Thank you for fixing this!
